 const USER_TYPES = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    
    CHANGE_PWD:"CHANGE_PWD",
    RECOVERY_PWD: "RECOVERY_PWD",
    LOGOUT: 'USERS_LOGOUT'
}


 const COURSE_TYPES = {
    LOADING:"LOADING",
    FIND_ALL:"FIND_ALL",
    FIND_ALL_ERROR: "FIND_ALL_ERROR"
}

export {USER_TYPES, COURSE_TYPES};